# Generated by Django 5.2.13 on 2026-04-26 09:08

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(db_index=True, max_length=256, unique=True)),
                ('hmac_secret', models.CharField(max_length=512)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vendor_credentials',
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(db_index=True, max_length=512, unique=True)),
                ('source_vendor', models.CharField(db_index=True, max_length=256, null=True)),
                ('raw_payload', models.JSONField()),
                ('status', models.CharField(choices=[('RECEIVED', 'received'), ('PROCESSING', 'processing'), ('COMPLETED', 'completed'), ('FAILED', 'failed')], db_index=True, default='RECEIVED', max_length=16)),
                ('event_type', models.CharField(choices=[('shipment', 'shipment'), ('invoice', 'invoice'), ('unclassified', 'unclassified')], max_length=32, null=True)),
                ('normalized_data', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('processed_at', models.DateTimeField(null=True)),
                ('error_message', models.TextField(null=True)),
                ('requires_review', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'webhook_events',
            },
        ),
        migrations.CreateModel(
            name='ShipmentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_id', models.CharField(max_length=256)),
                ('tracking_number', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=16)),
                ('timestamp', models.DateTimeField()),
                ('webhook_event', models.OneToOneField(db_column='webhook_event_id', on_delete=django.db.models.deletion.CASCADE, related_name='shipment_record', to='webhooks.webhookevent')),
            ],
            options={
                'db_table': 'shipments',
            },
        ),
        migrations.CreateModel(
            name='InvoiceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_id', models.CharField(max_length=256)),
                ('invoice_id', models.CharField(max_length=256)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('currency', models.CharField(max_length=3)),
                ('webhook_event', models.OneToOneField(db_column='webhook_event_id', on_delete=django.db.models.deletion.CASCADE, related_name='invoice_record', to='webhooks.webhookevent')),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
    ]
