# Generated by Django 5.2.13 on 2026-04-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['status', 'created_at'], name='webhook_status_created_idx'),
        ),
    ]
