# Generated by Django 5.2.13 on 2026-04-27 10:09

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_webhookevent_webhook_status_created_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookevent',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'received'), ('PROCESSING', 'processing'), ('COMPLETED', 'completed'), ('FAILED', 'failed')], default='RECEIVED', max_length=16),
        ),
    ]
