FROM python:3.12-slim AS builder

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev --no-install-project

COPY project/ project/
COPY webhooks/ webhooks/
COPY workflows/ workflows/
COPY manage.py ./

FROM python:3.12-slim

RUN groupadd --system app && useradd --system --gid app --uid 1000 app

WORKDIR /app

COPY --from=builder --chown=app:app /app /app
ENV PATH="/app/.venv/bin:$PATH"
ENV DJANGO_SETTINGS_MODULE="project.settings.prod"

USER app

CMD ["python", "manage.py", "run_worker"]
